# Pandas
Dataframe - Special Object to store data in tabluar form

In [2]:
import pandas as pd
import numpy as np

In [4]:
# Create a dataframe
# dictionary to data frame
user_data = {
    "MarksA": np.random.randint(1, 100, 5),
    "MarksB": np.random.randint(1, 100, 5),
    "MarksC": np.random.randint(1, 100, 5)
}

In [5]:
user_data

{'MarksA': array([ 6, 47, 61, 43, 68]),
 'MarksB': array([32, 63, 75, 30, 95]),
 'MarksC': array([ 1, 72, 65, 89,  9])}

In [7]:
# creating a table using this dictionary

df = pd.DataFrame(user_data)
print(df)

   MarksA  MarksB  MarksC
0       6      32       1
1      47      63      72
2      61      75      65
3      43      30      89
4      68      95       9


In [8]:
# to see the column header
print(df.columns)

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')


In [10]:
# convert the dataframe to a csv filev
df.to_csv('./files/marks.csv')

In [11]:
# reading csv into a df
df = pd.read_csv('./files/marks.csv')
df

Unnamed: 0  MarksA  MarksB  MarksC
0           0       6      32       1
1           1      47      63      72
2           2      61      75      65
3           3      43      30      89
4           4      68      95       9

In [13]:
# remove the first column
df.drop(df.columns[0], axis=1, inplace=True)
df

MarksA  MarksB  MarksC
0       6      32       1
1      47      63      72
2      61      75      65
3      43      30      89
4      68      95       9

In [15]:
# Extra Infromation about the data in the table
df.describe()

MarksA     MarksB     MarksC
count   5.000000   5.000000   5.000000
mean   45.000000  59.000000  47.200000
std    24.052027  28.008927  39.600505
min     6.000000  30.000000   1.000000
25%    43.000000  32.000000   9.000000
50%    47.000000  63.000000  65.000000
75%    61.000000  75.000000  72.000000
max    68.000000  95.000000  89.000000

In [26]:
# Access a particular row
print(df.head(3))   # top 3 rows
print("\n")
print(df.tail(3))   # bottom 3 rows
print("\n")
print(df.iloc[3])   # first row
print("\n")
print(df.iloc[3,1]) # index (row and column)
print(df.iloc[3][1]) # index (row and column)
print("\n")
print(df.iloc[3,[0,2]]) # 3th row, columns 0 and 2
print("\n")
print(df.iloc[:3,[0,2]]) # first 3 rows with columns 0 and 2



   MarksA  MarksB  MarksC
0       6      32       1
1      47      63      72
2      61      75      65


   MarksA  MarksB  MarksC
2      61      75      65
3      43      30      89
4      68      95       9


MarksA    43
MarksB    30
MarksC    89
Name: 3, dtype: int64


30
30


MarksA    43
MarksC    89
Name: 3, dtype: int64


   MarksA  MarksC
0       6       1
1      47      72
2      61      65


In [28]:
# Sort The dataframe

df.sort_values(by=['MarksC', 'MarksA'], ascending=False)

MarksA  MarksB  MarksC
3      43      30      89
1      47      63      72
2      61      75      65
4      68      95       9
0       6      32       1

In [29]:
# convert df to numpy arrray
myArray = df.values
print(myArray)

[[ 6 32  1]
 [47 63 72]
 [61 75 65]
 [43 30 89]
 [68 95  9]]


In [32]:
# covert numpy array to dataframe
new_df = pd.DataFrame(myArray, dtype= 'int32', columns=['MarksA', 'MarksB', 'MarksC'])
new_df

MarksA  MarksB  MarksC
0       6      32       1
1      47      63      72
2      61      75      65
3      43      30      89
4      68      95       9